### ISSUE TITLE
A directory for trained models

### ISSUE THREAD

**Issue by Trion129** [marco-c/autowebcompat#101]
If we train a model e.g. VGG16, it would be beneficial to have its pretrain.h5 available in a trained_weights directory.
e.g. in #96 , VGG16 from previous Siamese model can be used, with the first layer weights locked. The training and experimentation would get much faster this way.
This can work as a model zoo.

**Comment by vikasmahato** [comment]
Hi,
Can I work on this issue?

**Comment by marco-c** [comment]
Closing since it's not actually an issue.
