### ISSUE TITLE
Check if the collected image is of null size .

### ISSUE THREAD

**Issue by amit2rockon** [marco-c/autowebcompat#114]
Some null byte Images are collected which crashes pretrain.py/train.py .
For example, you can check 7815_firefox.png.
Deleting these null sized images fix the crashing issue.

**Comment by Shashi456** [comment]
@amit2rockon there is no 7815_firefox.png?

**Comment by Shashi456** [comment]
@amit2rockon also can you post a screenshot of this behaviour?

**Comment by amit2rockon** [comment]
![screen shot 2018-03-11 at 11 49 07 am](https://user-images.githubusercontent.com/22710677/37250426-57314682-2522-11e8-844c-80c06a0139fb.png)
 I have also faced this issue earlier and resolved by deleting those null files .

**Comment by sagarvijaygupta** [comment]
@amit2rockon can you run 7815 bug once again and check if it shows any error while taking the screenshot?

**Comment by Shashi456** [comment]
@sagarvijaygupta do you have 7815 in your data directory?

**Comment by Shashi456** [comment]
as far and having run the training.py/pre-train.py scripts i havent encountered this behaviour

**Comment by Shashi456** [comment]
@amit2rockon : we could do something like this to check if the loaded numpy array has some size i.e null or not
```  python:
img = load_img(os.path.join('./data/'+f), target_size=(32, 24))
    x = img_to_array(img, data_format=keras.backend.image_data_format())
    if x.size :
        continue
    else :
        print(f)
```

**Comment by sagarvijaygupta** [comment]
@Shashi456 no I don't have 7815. And even after running collect.py to get screenshot of 7815 I get this.
![screenshot from 2018-03-11 13-43-23](https://user-images.githubusercontent.com/19645459/37251237-422b46ec-2532-11e8-9a1e-d8932f4cbf5e.png)

Without any file generated for 7815.

**Comment by Shashi456** [comment]
@sagarvijaygupta when was it that you cloned the data directory?

**Comment by sagarvijaygupta** [comment]
@Shashi456  On 13th Feb.

**Comment by marco-c** [comment]
There's no 7815_firefox.png, so probably it's an issue with your local setup.
