### ISSUE TITLE
Dimensions of some images are like 412 × 24512 | 412 × 28868 | 412 × 19705 | 412 × 20474

### ISSUE THREAD

**Issue by amit2rockon** [marco-c/autowebcompat#115]
- 1134_0_firefox.png
- 1134_1_firefox.png
- 9409_1_firefox.png
- 9409_5_firefox.png
- 1527_firefox.png
- 1305_firefox.png
- 9409_firefox.png
example : 

![1134_1_firefox](https://user-images.githubusercontent.com/22710677/37256087-06ce5f68-257c-11e8-8881-d775c15c15e8.png)

**Comment by Shashi456** [comment]
@amit2rockon the issue being? Because as far as i know all images are resized before being trained

**Comment by amit2rockon** [comment]
@Shashi456  412 * xxxxx is resized to 192 *256 means xxxxx size vector is resized to 256 so clearly it is not possible to detect any difference even if the elements are interacted.

**Comment by marco-c** [comment]
We need to make sure these images are cut to the right height in `prepare_images`.

**Comment by hardik124** [comment]
@marco-c  Should we take image width as a standard and crop height accordingly? 
(say width is X we cut height as (X/192) * 256) ?

**Comment by marco-c** [comment]
We should crop the height to match the other images that don't have this problem.

**Comment by Trion129** [comment]
What could be causing such screenshots? 🤔

**Comment by hardik124** [comment]
@marco-c  Can I take this up?

**Comment by marco-c** [comment]
Sure

**Comment by sagarvijaygupta** [comment]
Should the cropping be simple like making them of same size directly or based on alignment using cross-correlation first and then cropping?

**Comment by marco-c** [comment]
It can probably be simple, just taking the top part of the image. It might be worth manually checking that it's the most correct thing to do (e.g. compare the Firefox and Chrome screenshot and see if after cropping they have the same view)
