### ISSUE TITLE
Store current page source and DOM tree alongside screenshots

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#117]
We might use this data in the future to improve the classification.

**Comment by vibss2397** [comment]
Hey, could i work on this?

**Comment by marco-c** [comment]
Sure!

**Comment by vibss2397** [comment]
Thanks,
also @marco-c i wanted to ask some questions about the proposal, where do you think would be a good place to discuss

**Comment by marco-c** [comment]
@vibss2397 you can contact me on IRC or via email. If you have ideas on additional things to implement, you can file an issue directly.

**Comment by vibss2397** [comment]
@marco-c  for storage do you think storing in a JSON file would suffice  which would contain different objects or should I make different text files for each screenshot

**Comment by marco-c** [comment]
One file for each screenshot, otherwise the JSON file would be huge.
