### ISSUE TITLE
When performing labeling, allow user to select the area of the image where the incompatibility lies

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#118]
With the current labeling system, we don't know where the incompatibilities lie but just whether there is at least an incompatibility or not.
This means we can't do things like training on clips of the images (because we wouldn't know if the clip contains an incompatibility or not).

We should store the areas where the incompatibilities lie alongside the labels.

**Comment by sagarvijaygupta** [comment]
@marco-c Can I take this one? I should add a tkinter based interface for the same?

**Comment by marco-c** [comment]
Sure! The current label.py can be modified, or if it is a pain to do it with tkinter you can use anything else.

**Comment by sagarvijaygupta** [comment]
@marco-c In that case I will try to use OpenCV. Is it fine?

**Comment by marco-c** [comment]
Yes, whatever you prefer/find easier to use.

**Comment by marco-c** [comment]
The only requirement is that the resulting UI must be simple enough to use for labeling.

**Comment by sagarvijaygupta** [comment]
What should be the labeling for screenshots which differ in language? Like this one

![screenshot from 2018-06-09 15-09-58](https://user-images.githubusercontent.com/19645459/41190153-57d69db4-6bf7-11e8-9c37-a37bad89e1b3.png)

**Comment by marco-c** [comment]
What is the URL for this case?

**Comment by marco-c** [comment]
I guess we should classify them as being different, since the language detection worked in one browser but not in the other.

**Comment by sagarvijaygupta** [comment]
Okay! So I should mark the bounding box around whole text? And in the English side only?

**Comment by marco-c** [comment]
> Okay! So I should mark the bounding box around whole text? And in the English side only?

Yes, around the text (and in this case the "NEXT" button too). In this case it looks like the English side is wrong, since the screenshots were collected on my machine.

**Comment by sagarvijaygupta** [comment]
Oh! So in all images where there is language difference I will mark bounding boxes on Italian side.

**Comment by marco-c** [comment]
I guess we can close this now, as it was done.
