### ISSUE TITLE
Investigate running multiple crawlers in parallel

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#12]
We should try to modify collect.py to run multiple instances of the browsers. Since the crawler is spending most of its time waiting (for the page to be fully loaded), running multiple instances can increase consistently the number of screenshots we can take per second.

**Comment by Vedarth** [comment]
@marco-c Do you mean running browsers on different threads? I can work on that.

**Comment by marco-c** [comment]
Yes. Right now we're running Firefox and Chrome in a single thread, we should try to run multiple threads (each one running Firefox and Chrome).

**Comment by Vedarth** [comment]
@marco-c Alright. I will try to implement that.

**Comment by sagarvijaygupta** [comment]
@Vedarth are you working on it?

**Comment by Vedarth** [comment]
@sagarvijaygupta yes i am. Will submit a pr after proper testing.
