### ISSUE TITLE
Update .gitignore, add .pytest_cache to it

### ISSUE THREAD

**Issue by poush** [marco-c/autowebcompat#124]
Also, I think the `.idea` created by Jetbrains editor should be added to the .gitignore.

@marco-c Please confirm it and add this as good first issue.

**Comment by marco-c** [comment]
Yes, sounds good.

**Comment by sdv4** [comment]
May I be assigned to this issue?

**Comment by marco-c** [comment]
Sure, feel free to submit a PR.
