### ISSUE TITLE
Minor bug in VGG16 block in network.py

### ISSUE THREAD

**Issue by ManasviKundalia** [marco-c/autowebcompat#134]
In block 2 of the create_vgg16_network function, line 39 should be 
`x = MaxPooling2D(pool_size=(2, 2), strides=(2, 2))(x)`
instead of just 
`MaxPooling2D(pool_size=(2, 2), strides=(2, 2))(x)`
It is missing the equality.

**Comment by marco-c** [comment]
Thanks for noticing, probably a regression from a refactoring.
