### ISSUE TITLE
Removing Deformed labels from the labels.csv 

### ISSUE THREAD

**Issue by Shashi456** [marco-c/autowebcompat#140]
Labels.csv has some file names which are not present in images , probably caused due to some error while writing .
Namely : 
3516_rfc.index
10108_a-albumset-push.0

**Comment by marco-c** [comment]
Can you check if there's any file starting with `3516` or `10108` in the data directory?

**Comment by Shashi456** [comment]
@marco-c  yeah multiple files for both formats
