### ISSUE TITLE
Investigate if we can repeat the same steps in different browsers without element IDs

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#15]
Right now, we only interact with elements that have an ID and store the sequence of operations as a list of element IDs.
A lot of times on websites the elements don't have an ID though. Can we find a way to repeat the same steps that we perform in a browser on another browser without having the IDs of the elements?

**Comment by sagarvijaygupta** [comment]
@marco-c  we can try using the absolute ```XPath```. I think it should work.

**Comment by marco-c** [comment]
> @marco-c we can try using the absolute XPath. I think it should work.

We can try, the only problem is that I'm not sure it's supported exactly in the same way across browsers.

**Comment by sagarvijaygupta** [comment]
@marco-c I was also searching about that only. It feels it won't be that feasible.

Though I found a much **better idea**!
 Considering we have all children with which we feel we can interact with, we can store all the attributes of that child we wish to work with even if it doesn't have ID. 
So keeping this sequence saved we can than search all the elements in the next browser and match with all the attributes. 
If they come out to be same we follow the sequence.
Below is the code to get all the attributes of element - child

` all_attributes_of_child = driver.execute_script
('
var elem_attribute = {};
for (i = 0; i < arguments[0].attributes.length; i++) 
 { 
         elem_attribute[arguments[0].attributes[i].name] = arguments[0].attributes[i].value
 }; 
         return  elem_attribute;
', child)`

This file contains output for both firefox and chrome of all attributes. Please take a look and tell me if this idea is feasible? 
[firefox_chrome.txt](https://github.com/marco-c/autowebcompat/files/1687265/firefox_chrome.txt)

**Comment by sagarvijaygupta** [comment]
@marco-c any thoughts on this?

**Comment by sagarvijaygupta** [comment]
@marco-c  any thoughts on this?

**Comment by sagarvijaygupta** [comment]
@marco-c  Please give a review on this idea? I wish to work on it.

**Comment by marco-c** [comment]
The idea sounds good to me. I think we should keep both the ID version and add this capability too.
We should create a file alongside the screenshot to tell how the screenshot was generated (so that we can re-generate it if needed). Also the naming of the screenshots needs to change, as it currently contains the IDs.
It would be great if you could rewrite that script in Python, but doing it on the JavaScript side is fine too.

**Comment by marco-c** [comment]
The screenshot naming could be:
WEBCOMPAT-ID_BROWSER.png for the first load screenshots;
WEBCOMPAT-ID_ELEMENT-ID_SEQUENCE-NUM_BROWSER.png for the screenshots generated using the element IDs;
WEBCOMPAT-ID_SEQUENCE-NUM_BROWSER.png for the screenshots generated using this method (and a WEBCOMPAT-ID_SEQUENCE-NUM.txt file containing the attributes should be generated alongside it).

I suggest we do it this way so that we don't have to rename all current data files.

**Comment by sagarvijaygupta** [comment]
@marco-c should I keep a file ```WEBCOMPAT-ID_SEQUENCE-NUM.txt``` for every screenshot or should I create one file and keep on appending a dictionary of type ```image_file_name : attributes```

**Comment by marco-c** [comment]
As you prefer. Maybe a single file is better, to avoid creating too many files in the data/ directory.

**Comment by sagarvijaygupta** [comment]
![999999999999999999_6_chrome](https://user-images.githubusercontent.com/19645459/35935731-5dd1fe4c-0c67-11e8-9259-c6aae2ee6553.png)
![999999999999999999_5_chrome](https://user-images.githubusercontent.com/19645459/35935732-5e167310-0c67-11e8-81c8-8baf499a1c38.png)
![999999999999999999_4_chrome](https://user-images.githubusercontent.com/19645459/35935734-5e58eefc-0c67-11e8-9f7c-2329a4e1d13c.png)
![999999999999999999_3_chrome](https://user-images.githubusercontent.com/19645459/35935736-5ec1227e-0c67-11e8-8078-2aac262f2235.png)
![999999999999999999_2_chrome](https://user-images.githubusercontent.com/19645459/35935737-5f13ec20-0c67-11e8-9456-5cbbf2000c4d.png)
![999999999999999999_1_chrome](https://user-images.githubusercontent.com/19645459/35935738-5f71e604-0c67-11e8-9c09-029c174dac91.png)
![999999999999999999_0_chrome](https://user-images.githubusercontent.com/19645459/35935741-5fda8c18-0c67-11e8-8733-96a38a9182d0.png)
![999999999999999999_chrome](https://user-images.githubusercontent.com/19645459/35935745-60395b1c-0c67-11e8-9b98-05220b4b8149.png)
![999999999999999999_6_firefox](https://user-images.githubusercontent.com/19645459/35935746-6087ac54-0c67-11e8-8e24-32a4968682c9.png)
![999999999999999999_5_firefox](https://user-images.githubusercontent.com/19645459/35935748-60cbf90e-0c67-11e8-9627-4ccc3ee34564.png)
![999999999999999999_4_firefox](https://user-images.githubusercontent.com/19645459/35935750-61a4fd1c-0c67-11e8-8d43-9a8ee339aae8.png)
![999999999999999999_3_firefox](https://user-images.githubusercontent.com/19645459/35935753-61fcce34-0c67-11e8-8ce6-18e476cd2bf7.png)
![999999999999999999_2_firefox](https://user-images.githubusercontent.com/19645459/35935754-6233ed10-0c67-11e8-9a26-2a792a86c2eb.png)
![999999999999999999_1_firefox](https://user-images.githubusercontent.com/19645459/35935756-6272e718-0c67-11e8-8bf9-2e1888dc9076.png)
![999999999999999999_0_firefox](https://user-images.githubusercontent.com/19645459/35935757-62cc79a4-0c67-11e8-9407-0e40e569beb0.png)
![999999999999999999_firefox](https://user-images.githubusercontent.com/19645459/35935759-6323ed24-0c67-11e8-83d9-20c262ec732f.png)

@marco-c These are the screenshots for github.com. This way it actually finds much more objects. 
Should I create a script which reads ```image_info.txt``` and takes image name as input and prints all attributes as output?

**Comment by marco-c** [comment]
Actually, instead of creating one file per screenshot or one file only, let's create one file per webcompat-id.
No need for the script for now.

**Comment by marco-c** [comment]
Fixed by #41.
