### ISSUE TITLE
Unable to run train.py

### ISSUE THREAD

**Issue by sagarvijaygupta** [marco-c/autowebcompat#178]
I have been trying to run `train.py` for some time and I am unable to do so. 

1. In `CoupleIterator` in `x1 = load_image(i1)`,  `i1` is itself a `numpy array` so calling `load_image` gives an error.
2. Even if I change `x1 = load_image(i1)` to `x1 = i1` I am getting accuracy = 0 and sometimes my laptop crashes.
I needed to know anything I am missing while running it?
` python train.py vgglike sgd 'Y vs N + D' `

**Comment by Shashi456** [comment]
I dont think its a faut in the ```CoupleIterator``` since the same is working with pretrain.py

**Comment by marco-c** [comment]
Fixed by a6649e5 and c183665.
