### ISSUE TITLE
Change argparse interface for train.py

### ISSUE THREAD

**Issue by sagarvijaygupta** [marco-c/autowebcompat#182]
So that `train.py` runs like:

>  python train.py --network=vgg16 --optimizer=adam --classification_type='Y vs D + N'
 python train.py -n=vgg16 -o=adam -ct='Y vs D + N'

**Comment by Shashi456** [comment]
Shouldn't we similarly change it for the pretrain.py as well @sagarvijaygupta @marco-c

**Comment by marco-c** [comment]
Yes!
