### ISSUE TITLE
Labeling Guidelines Format issue

### ISSUE THREAD

**Issue by Shashi456** [marco-c/autowebcompat#222]
When I ran label.py on my pc , i saw that the ```terminal_color``` class variables do not get read properly. 
I have a windows 10 operating system.

![image](https://user-images.githubusercontent.com/18056781/41791382-35cbded8-7673-11e8-839e-8b7e2537199e.png)

**Comment by sagarvijaygupta** [comment]
I never tested it on windows. It runs fine on Linux.

**Comment by Shashi456** [comment]
@sagarvijaygupta  Windows terminal doesn't handle ansi coding for colouring text like other (vt100 compatible) terminals. 

there's a solution of using packages like colorama or ansicon. but I think that would be quite unnecessary

**Comment by sagarvijaygupta** [comment]
@Shashi456  I didn't want to add any dependency so followed this approach. I think its better to add a platform check or remove it all at once.

**Comment by Shashi456** [comment]
@sagarvijaygupta yeah additional dependencies just for a display sounds like a hassle, removing it may be the way to go

**Comment by sagarvijaygupta** [comment]
@marco-c What do you think?

**Comment by marco-c** [comment]
Yeah we can just remove them, they are just fancy additions.
For both keys and colors, let's just wrap them between *.
