### ISSUE TITLE
test_labels.py is not actually testing the screenshots actually exist

### ISSUE THREAD

**Issue by sagarvijaygupta** [marco-c/autowebcompat#245]
https://github.com/marco-c/autowebcompat/blob/9dd4b2b38025920324ba0bbcb45fe307a51bdf72/tests/test_labels.py#L10

Should be changed to 

> os.path.exists(os.path.join('data', '{}_{}.png'.format(label, browser)))

**Comment by sagarvijaygupta** [comment]
5478_4
5478_4
5991
6081_3
6081_3
7490_4
7490_4
8371
8371
9084_6
9084_6
@marco-c these labels are present in your csv file but not uploaded in gitlab

**Comment by marco-c** [comment]
>  @marco-c these labels are present in your csv file but not uploaded in gitlab

Ah yes, it's because I have some additional screenshots on my machine that I haven't pushed yet...

**Comment by marco-c** [comment]
Since they are just a few, would you mind removing them manually as part of https://github.com/marco-c/autowebcompat/pull/246?
