### ISSUE TITLE
Improve user-experience of get_dependencies.py

### ISSUE THREAD

**Issue by SkullTech** [marco-c/autowebcompat#25]
The `get_dependencies.py` script prints no message, and takes a long time to finish its execution (as it involves downloading and extracting a zip file of size 1.4 GB). So while the script runs, it results in a poor experience of the user (as he doesn't know what's going on, and it gives off the impression that it's stuck). It can be improved by

- Printing some info while the execution occurs.
- Showing a progress bar while it downloads the `data.zip` file.

The progress bar can be added using libraries like [`clint`](https://github.com/kennethreitz/clint), but it also means adding an extra dependency. Although, as we polish this project, we will be needing proper CLI interface, so it won't hurt if we start adding them now.

**Comment by marco-c** [comment]
For the progress bar, we could implement it ourselves with a few lines of code to avoid the dependency, something like https://gist.github.com/vladignatyev/06860ec2040cb497f0f3.
After all, we are probably never going to need any fancy cli feature othern than a simple argparse.

**Comment by SkullTech** [comment]
Yes, you're right. Using `clint` and all would be overdoing it.
