### ISSUE TITLE
Rearrange the project directory structure

### ISSUE THREAD

**Issue by SkullTech** [marco-c/autowebcompat#37]
Rearrange it into a structure like [this](https://docs.pytest.org/en/latest/goodpractices.html#tests-outside-application-code), as suggested by @marco-c [here](https://github.com/marco-c/autowebcompat/pull/36#discussion_r166479187). This will facilitate testing, among other things.

**Comment by poush** [comment]
Can I take this up?

**Comment by marco-c** [comment]
Sure!

**Comment by nok** [comment]
Please be inspired by https://drivendata.github.io/cookiecutter-data-science/#directory-structure 😉

**Comment by poush** [comment]
I think we can have project structure similar to this:


> ├── LICENSE
> ├── README.md
> ├── __pycache__
> │   └── ...
> **├── autowebcompat
> │   ├── __init__.py
> │   ├── network.py
> │   ├── utils.py**
> ├── data [17950 entries exceeds filelimit, not opening dir]
> ├── geckodriver.log
> ├── label_persons
> │   └── amit2rockon.csv
> ├── labels.csv
> ├── requirements.txt
> **├── scripts
> │   ├── collect.py
> │   ├── data_inconsistencies.py
> │   ├── generate_labels.py
> │   ├── get_dependencies.py
> │   ├── label.py
> │   ├── pretrain.py
> │   └── train.py**
> ├── setup.cfg
> ├── test-requirements.txt
> ├── tests
> │   └── __init__.py
> ├── tools
> │   ├── Nightly.app
> │   ├── chrome.app
> │   ├── chromedriver
> │   └── geckodriver
> └── webcompatdata-bzlike.json

**Comment by poush** [comment]
scripts based files apart from network.py and utils.py shifted to scripts/ directory for now. Once we transform them into OOP style then we can put it back on `autowebcompat`. 

Please let me know how it can be improved more.

**Comment by poush** [comment]
@nok Thanks, I will check it out.

**Comment by marco-c** [comment]
The structure looks good to me. Either with the scripts in the top-level directory or in the `scripts` subdirectory.
