### ISSUE TITLE
Changes to complete code structure and format for better usage of Networks in both training and testing.

### ISSUE THREAD

**Issue by Zzoey** [marco-c/autowebcompat#38]
1. Following Pycode style guidelines.
https://pypi.python.org/pypi/pycodestyle

2. Classes for the Siamese module in order to the same module for different type of networks and on different datasets. Can make ease of parallelisation for quick results.

3. Function naming should be standardised accordingly.

**Comment by nok** [comment]
Great suggestions!

In addition we could use cookiecutter which can scaffold a basic data science project:
https://drivendata.github.io/cookiecutter-data-science#directory-structure

**Comment by Shashi456** [comment]
@marco-c  how would this probably be done? is it one entire file at a time? or does this issue need to be updated with a task list?

**Comment by marco-c** [comment]
Let's close this and refactor things as we see fit.
