### ISSUE TITLE
Support 'search' input type in the crawler

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#5]
https://github.com/marco-c/autowebcompat/blob/e3f77c7b48e017a0ddfe0116e8748964d36fa74c/collect.py#L104

**Comment by ManasviKundalia** [comment]
@marco-c Could you elaborate this issue? I didn't quite get what is to be done here

**Comment by marco-c** [comment]
The crawler currently doesn't support [search input types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search). We need to add support for it (close to the line mentioned in the first comment).
It also has to be tested with some website that has a search input type (you can use the MDN docs page).

**Comment by ManasviKundalia** [comment]
@marco-c okay! I will work on it.
