### ISSUE TITLE
Make the crawler check if screenshots for the operations were taken

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#54]
Right now, for each webcompat issue, we are just checking if we have taken screenshots for the main page. We should instead check if we have taken screenshots for all the possible operations too.

Basically, this should take care of the TODO here:
https://github.com/marco-c/autowebcompat/blob/5bb234eaac7bfbcb42bb5b6b6740d03adec6df35/collect.py#L220

Given the associated text file with the sequence of operations, we should check if a screenshot exist for every operation. When a screenshot doesn't exist, we should attempt to create it.

**Comment by sviter** [comment]
I think I can do this.

**Comment by Shashi456** [comment]
Can i take this up?

**Comment by marco-c** [comment]
> Can i take this up?

Seems like @sviter was interested too, can you find another issue to work on? Or see if @sviter wants to pick something else up.
