### ISSUE TITLE
Add UTF-8 Encoding to get_dependencies.py

### ISSUE THREAD

**Issue by poush** [marco-c/autowebcompat#58]
On running `python get_dependencies.py` we get an error as:

```
File "get_dependencies.py", line 31
SyntaxError: Non-ASCII character '\xe2' in file get_dependencies.py on line 31, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

To solve this, the utf-8 encoding should be mentioned on get_dependencies.py

**Comment by marco-c** [comment]
The project is requiring Python 3, where defining the encoding is not strictly necessary (it should be UTF-8 by default).
