### ISSUE TITLE
Add unit tests for the functions in utils.py

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#6]

**Comment by SkullTech** [comment]
@marco-c Which testing framework should we use for this project? I suggest [`pytest`](https://docs.pytest.org/en/latest/), it's one of the most robust ones out there.

**Comment by SkullTech** [comment]
I can start working on this once we've decided on the framework to use.

**Comment by marco-c** [comment]
👍 for pytest!

**Comment by SkullTech** [comment]
Okay will start working on it ASAP. :D

**Comment by marco-c** [comment]
Since @SkullTech already has some experience with the project, it's better if someone else who is just starting takes this on to gain some experience.

**Comment by Shashi456** [comment]
Can i take this up ?

**Comment by marco-c** [comment]
Sure, go ahead!

**Comment by Shashi456** [comment]
I wanted to know if these are the following unit tests are okay ? And i'm only majorly checking for functions with some parameters

`def test_mkdir():
    direc_path = os.path.dirname(os.path.realpath(__file__)) + "test"
    mkdir(direc_path)
    assert(os.path.exists(direc_path))`

`
def test_read_labels():
    labels = read_labels(file_name='labels.csv')
    assert('labels' in locals() or 'labels' in globals() )`


`def test_write_labels():
    write_labels(label,file_name='test.csv')
    fname = os.path.dirname(os.path.realpath(__file__)) + "\\test.csv"
    assert(os.path.exists(fname))`

**Comment by marco-c** [comment]
Hey @Shashi456, please write a PR, it's easier to review than a comment in an issue!
For creating directories and files, I suggest you put everything in a temporary directory (you can use the `tempfile` library) and clean everything at the end of the test.
