### ISSUE TITLE
Support 'submit' input type in the crawler

### ISSUE THREAD

**Issue by ManasviKundalia** [marco-c/autowebcompat#65]
Around line 159
`elif input_type == 'radio':
elem.click()`

**Comment by yash-iiith** [comment]
What happens when the input type is 'submit'? I mean what should be there in the elif statement for 'submit'?

**Comment by marco-c** [comment]
> What happens when the input type is 'submit'? I mean what should be there in the elif statement for 'submit'?

They are basically buttons, so they should be clicked.
