### ISSUE TITLE
Support select tags in the crawler

### ISSUE THREAD

**Issue by poush** [marco-c/autowebcompat#67]
In collect.py add ability to support select tags

**Comment by vikasmahato** [comment]
Hi,
Can I work on this?

**Comment by marco-c** [comment]
Sure, go ahead!

**Comment by vikasmahato** [comment]
@marco-c can you please review this and suggest changes?
https://github.com/marco-c/autowebcompat/pull/100

**Comment by marco-c** [comment]
Fixed by #100.
