### ISSUE TITLE
Expand the write_labels/read_labels tests to make sure read_labels can read labels written by write_labels

### ISSUE THREAD

**Issue by Shashi456** [marco-c/autowebcompat#68]
The test_write_labels test in the test_utils.py file just simply asserts the existence of the file, a new test should be written or the same updated. This test should write the labels and then read them back. The read labels should be the same as the written ones. 

See also PR #63.

**Comment by vikasmahato** [comment]
@marco-c  Can I work on this?

**Comment by marco-c** [comment]
@vikasmahato this is reserved for people who haven't made any contribution yet.

**Comment by vikasmahato** [comment]
No problem :)
