### ISSUE TITLE
Try using a network pretrained on ImageNet (e.g. VGG16)

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#7]
Docs: https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html.

We should try both using the output of the network as features, and finetuning the top layers and finetuning all layers.

**Comment by Shashi456** [comment]
Although transfer learning might work in this , we'd have to finetune pretty deep into the network to make it work for this usecase . VGG16 was trained on 1000 classes of dogs and cats so finetuning just the top layers for this usecase might not work.

**Comment by Shashi456** [comment]
@marco-c  can we make a list of architectures not tried yet?

**Comment by marco-c** [comment]
@Shashi456 anything that is not in `network.py` has not been tried yet.

**Comment by marco-c** [comment]
If you have an idea for a specific network, you can file an issue and mention this one.

**Comment by Shashi456** [comment]
@marco-c  has any networked pretrained on image-net(like vgg16 or inception) been run for this, the network.py although includes vgg i dont know if transfer learning has been tested?

**Comment by marco-c** [comment]
No, not yet.

**Comment by vikasmahato** [comment]
Hi @marco-c 
I am interested in working on this issue.

**Comment by marco-c** [comment]
@vikasmahato go ahead. Choose a network you want to try, file an issue about it and link the issue to this issue.

**Comment by Shashi456** [comment]
@marco-c  in the create network function in networks.py i see that we can load weights onto the network, have we tried that for vgg16 yet ?

**Comment by marco-c** [comment]
No, nobody has tried that yet. If you do, please file an issue and link it here.

**Comment by marco-c** [comment]
Closing in favor of #194.
