### ISSUE TITLE
Use the PyTest tmpdir feature instead of manually handling temporary directories through tempfile

### ISSUE THREAD

**Issue by Shashi456** [marco-c/autowebcompat#70]
There's a nice pytest feature that you can use instead of manually using tempfile: https://docs.pytest.org/en/latest/tmpdir.html.

See also PR #63.

**Comment by poush** [comment]
@marco-c Can I take this up?

**Comment by marco-c** [comment]
> @marco-c Can I take this up?

This is reserved for newcomers (people who haven't touched the code base yet) for the time being. You can pick it up if in a week nobody else has.
