### ISSUE TITLE
Improve documentation in the README

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#77]
The documentation is pretty scarce, it needs to be improved.

**Comment by Shashi456** [comment]
@marco-c What exactly are we looking for in the documentation? Should i start with #2  and elaborate on the problem statement first for a start?

**Comment by marco-c** [comment]
I'm working on this myself. If you want, you can improve on the documentation I'm writing.

**Comment by Shashi456** [comment]
@marco-c  Alright

**Comment by marco-c** [comment]
This is now fixed, feel free to suggest additions if you want.

**Comment by Shashi456** [comment]
@marco-c I had two suggestions for the documentation, one if we can document how to run the project locally? and the other if we could add a few lines at the top which talk about web compatibility briefly and then redirecting to some other page for some extra info.

**Comment by marco-c** [comment]
> @marco-c I had two suggestions for the documentation, one if we can document how to run the project locally?

What would you write?

> and the other if we could add a few lines at the top which talk about web compatibility briefly and then redirecting to some other page for some extra info.

There's a link now that brings you to a description of Web Compatibility.

**Comment by Shashi456** [comment]
@marco-c 
Something after get dependencies that the train / pretrain.py can be run directly to check how the current network fairs? 

and also updating the structure of the project to explain about the rest of the files which have come up recently ? or is that not required?

**Comment by marco-c** [comment]
> Something after get dependencies that the train / pretrain.py can be run directly to check how the current network fairs?

I think this should be clear from the description of the structure of the project, but we can add a short sentence.

> and also updating the structure of the project to explain about the rest of the files which have come up recently ? or is that not required?

It's not required, but not forbidden either :smile: 

Feel free to submit PRs for any addition you think worth adding.
