### ISSUE TITLE
Update data_inconsistencies.py script to account for changes in screenshot naming structure

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#78]
#41 broke the data_inconsistencies.py script. We should modify it to make it work again.

**Comment by Shashi456** [comment]
@marco-c can you tell me about the current screenshot naming convention?

**Comment by marco-c** [comment]
This is the current naming convention: https://github.com/marco-c/autowebcompat/pull/41#issuecomment-364139567.
