### ISSUE TITLE
Add argparse interface to pretrain.py and train.py to select network architecture and optimizer

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#79]
Two steps here:
1) Add a function to network.py that returns the list of supported networks and a function that returns the list of supported optimizers;
2) Add [argparse](https://docs.python.org/3/library/argparse.html) interface to pretrain.py and train.py to select network and optimizer from those lists.

**Comment by alisha17** [comment]
I am working on this issue.

**Comment by marco-c** [comment]
@alisha17 are you still working on this?

**Comment by alisha17** [comment]
@marco-c If anyone wants to work on it feel free, because it will take me time..too caught up in university assignments. Sorry :(

**Comment by marco-c** [comment]
OK. No worries, you can take your time.

**Comment by Trion129** [comment]
This would be very beneficial! I'll work on it

**Comment by marco-c** [comment]
@Trion129 if you can find another issue that nobody else has claimed yet, it would be better.

**Comment by Trion129** [comment]
Ah sure, no problems 😄
