### ISSUE TITLE
Add support for input type 'color'

### ISSUE THREAD

**Issue by poush** [marco-c/autowebcompat#81]
Like  different actions we can add `color` input type as well.

**Comment by poush** [comment]
@marco-c Are you sure that 'testing' label is relevant for this PR?

**Comment by marco-c** [comment]
> @marco-c Are you sure that 'testing' label is relevant for this PR? I think 'crawler' is good one here.

Good catch!

**Comment by Trion129** [comment]
Hi can I take this issue? would help me get started with the code :) Planning to contribute to autowebcompat in GSoC

**Comment by marco-c** [comment]
> Hi can I take this issue? would help me get started with the code :) Planning to contribute to autowebcompat in GSoC

Sure, go ahead!

**Comment by Trion129** [comment]
Can be closed, as it is fixed
