### ISSUE TITLE
Make sure there's only one element on the page with the given attributes

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#86]
In the first browser, when the crawler finds an element, it should check if there's no other element on the page with the same attributes.

In the second browser, when we are repeating the steps, we should assert that there's a single element on the page with the given attributes.

**Comment by ManasviKundalia** [comment]
@marco-c I will work on this

**Comment by marco-c** [comment]
@ManasviKundalia sorry I missed your comment. That's correct!

**Comment by sagarvijaygupta** [comment]
@ManasviKundalia are you working on this issue?

**Comment by ManasviKundalia** [comment]
@sagarvijaygupta yes
