### ISSUE TITLE
In data_inconsistencies.py, print how many screenshots we have collected and how many we could have collected

### ISSUE THREAD

**Issue by Shashi456** [marco-c/autowebcompat#87]
@marco-c 
Once #78  is fixed, I think a script should be written which ensures that inconsistent data is excluded and/or what part of the data collected is actually being used to train so that we have an idea of how successful we are at data collection and maybe update the crawler script later on.
Although i do know that labels.py will only take a set of images if both are present, i haven't seen any enforcement measures.

**Comment by marco-c** [comment]
The functions in utils.py should already be taking this into account.

**Comment by Shashi456** [comment]
@marco-c  Do all of them do this already? and what do you think about having the data coverage function, i think a measure of how successful we are at dataset collection could help us in the long run

**Comment by marco-c** [comment]
> @marco-c Do all of them do this already?

Yes, the ones we care about.

> and what do you think about having the data coverage function, i think a measure of how successful we are at dataset collection could help us in the long run

Do you mean the number of webcompat bugs we haven't taken screenshots for yet? Yes, that sounds useful.

**Comment by Shashi456** [comment]
> Do you mean the number of webcompat bugs we haven't taken screenshots for yet? Yes, that sounds useful.

Yeah, I meant this. Do we take any note of what bugs we've collected for yet?

But also I was pointing at the fact that, if we are collecting about 1000 set of images through our crawler and then some say 100 sets are inconsistent, we are only using 90% of the collection. I think a measure of this could help us in the long run.

**Comment by marco-c** [comment]
Yes, a script to see how many we have collected can definitely be useful.

**Comment by marco-c** [comment]
This can be part of the data_inconsistencies.py script.
