### ISSUE TITLE
Document that Git LFS is required and how to clone the repo with submodules

### ISSUE THREAD

**Issue by Trion129** [marco-c/autowebcompat#98]
On doing a fresh recursive clone of autowebcompat, the submodule for data fetches the `.png` files by filename but inside they have git signatures instead of content.
So it downloaded just 5MB data instead of 959MB.

How to reproduce bug:
1. `git clone --recurse-submodules git@github.com:marco-c/autowebcompat.git autoweb`
2. `cat autoweb/data/7_firefox.png`

![image](https://user-images.githubusercontent.com/8445249/36851607-99cea9a2-1d8f-11e8-96e2-67c747e00974.png)

It is text instead of png binary gibbrish!

**Comment by marco-c** [comment]
The repository is using Git LFS. Have you installed it on your machine?

**Comment by Trion129** [comment]
Oh, that makes sense! Nope I didn't know Git LFS is a thing. Although it should be in the Readme's setup section, there might be more people that don't know about LFS.
